# sample environment containing most important libraries
channels:
- defaults
- conda-forge
- districtdatalabs
dependencies:
- python=3.6.6
- numpy=1.14.5
- scipy=1.1.0
- scikit-learn=0.20.0
- jupyter=1.0.0
- pandas=0.23.4
- nltk=3.3.0
- ipykernel=4.10.0
- scikit-plot
- scikit-optimize
- pathlib
- keras=2.2.2
- pip:
  - xgboost
  - bayesian-optimization


