# sample environment containing most important libraries
channels:
- defaults
- conda-forge
- districtdatalabs
dependencies:
- python=3.6.6
- numpy=1.14.5
- scipy=1.1.0
- scikit-learn=0.20.0
- scikit-image=0.14.0
- tornado=4.5.3
- jupyter=1.0.0
- jupyterlab=0.34.9
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
- requests=2.18.4
- pandas=0.23.4
- pandas-profiling=1.4.0
- graphviz=2.38.0
- gensim=3.4.0
- seaborn=0.9.0
- cython=0.28.3
- nltk=3.3.0
- sqlalchemy=1.2.8
- plotly=3.2.1
- autopep8
- pylint
- pep8=1.7.1
- tqdm=4.23.4
- pylama=7.4.3
- langdetect=1.0.7
- notebook=5.6.0
- ipykernel=4.10.0
- ipywidgets=7.4.1
- nbconvert=5.4.0
- spacy=2.0.16
- pyhamcrest=1.9.0
- regex=2018.01.10
- statsmodels=0.8.0
- wordcloud=1.5.0
- pydot
- catboost=0.10.2
- yellowbrick
- tpot
- scikit-mdr
- skrebate
- scikit-plot
- scikit-optimize
- bz2file=0.98
- pathlib
- keras=2.2.2
- pip=18.0
- pillow=5.3.0
- lime
- pip:
  - xgboost
  - bayesian-optimization
  - pycryptodome==3.6.1


